import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Login from "../../components/auth/login";
import Register from "../../components/auth/register";

export default function AuthPage(props) {
  const [login, setLogin] = useState(true);
  const handleToggle = () => {
    setLogin(!login);
  };
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>
      <div className=" grid justify-center">
        {login ? (
          <Login handleToggle={handleToggle} />
        ) : (
          <Register handleToggle={handleToggle} />
        )}
      </div>
    </div>
  );
}
