import Head from "next/head";
import React, { Fragment } from "react";
import CreateAddForm from "../../components/create-add/create-add-form";
import { useSession, getSession } from "next-auth/react";
export default function CreateAddPage() {
  const { data: session } = useSession();
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Create Advertise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>

      <div className="grid justify-center">
        <CreateAddForm />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }
}
