import Head from "next/head";
import React, { Fragment } from "react";
import CreateAddForm from "../../components/create-add/create-add-form";

const CreateAddPage = () => {
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Create Advertise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>

      <div className="grid justify-center">
        <CreateAddForm />
      </div>
    </div>
  );
};

export default CreateAddPage;
