import Head from "next/head";
import React, { Fragment } from "react";
import FeaturedPosts from "../../components/home/featured-posts";
// import { connectToDatabase } from "../../lib/db";

export default function AdvertisePage(props) {
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Casa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>
      <h1 className="max-w-7xl mx-auto p-10 pb-0 font-semibold text-3xl text-gray-200">
        All Advertises
      </h1>
      <FeaturedPosts posts={props.posts} />
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(`http://localhost:5000/post/posts`);
  const data = await res.json();

  // Pass data to the page via props
  return {
    props: {
      posts: data,
    },
  };

  // const client = await connectToDatabase();
  // const db = client.db();
  // const postsData = await db.collection("posts").find().toArray();

  // const posts = JSON.parse(JSON.stringify(postsData));
  // // Pass data to the page via props
  // return {
  //   props: {
  //     posts: posts,
  //   },
  // };
}
