import Head from "next/head";
import React, { Fragment } from "react";

import Profile from "../../components/profile/profile";

const ProfilePage = () => {
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>

      <Profile />
    </div>
  );
};

export default ProfilePage;
