import Head from "next/head";
import React, { Fragment } from "react";
import { useSession, getSession } from "next-auth/react";
import { connectToDatabase } from "../../lib/db";
import Profile from "../../components/profile/profile";

export default function ProfilePage({ user }) {
  const { data: session } = useSession();

  if (session) {
    return (
      <div className="page bg-gray-900">
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/logo2.png" />
        </Head>

        <Profile user={user[0]} />
      </div>
    );
  }
  return (
    <Fragment>
      <div className="page bg-gray-900">
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/logo2.png" />
        </Head>

        <div className="p-8  grid place-items-center content-start min-h-screen">
          <p>Access Denied</p>
        </div>
      </div>
    </Fragment>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (session) {
    const client = await connectToDatabase();
    const db = client.db();

    const userData = await db
      .collection("users")
      .find({
        email: session.user.email,
      })
      .toArray();
    client.close();

    return {
      props: {
        user: userData.map((user) => ({
          email: user.email,
          name: user.name,
          status: user.status,
          gender: user.gender,
          profilePic: user.profilePic,
          posts: user.posts,
        })),
        session: session,
      },
    };
  } else {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }
}
