import Head from "next/head";
import Image from "next/image";
import FeaturedPosts from "../components/home/featured-posts";

export default function Home(props) {
  return (
    <div className="page bg-gray-900">
      <Head>
        <title>Casa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo2.png" />
      </Head>
      <h1 className="max-w-7xl mx-auto p-10 pb-0 font-semibold text-3xl text-gray-200">
        Featured
      </h1>
      <FeaturedPosts posts={props.posts} />
    </div>
  );
}

export async function getStaticProps() {
  // Fetch data from external API
  const res = await fetch("http://localhost:5000/post/posts", {
    method: "GET",
    headers: {
      // update with your user-agent
      "User-Agent":
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
      Accept: "application/json; charset=UTF-8",
    },
  });
  const posts = await res.json();

  // Pass data to the page via props
  return {
    props: {
      posts: posts.filter((p) => {
        if (p.isFeatured) {
          return true;
        }
        return false;
      }),
    },
  };
}
